name: bench
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  bench:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16"
      - run: go version
      - name: Build
        run: |
          go run .
      - uses: actions/upload-artifact@v2
        with:
          name: publish
          path: publish/*
          if-no-files-found: error
      - name: publish
        if: github.ref == 'refs/heads/main'
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_PUBLISH_TOKEN: ${{ secrets.VERCEL_PUBLISH_TOKEN }}
        run: |
          cd publish
          npx vercel --prod -f -c -C -t $VERCEL_PUBLISH_TOKEN
